# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

import torch
import torch.nn.functional as F
from torch import nn

from rsl_rl.algorithms import PPO
from rsl_rl.utils import unpad_trajectories


class RangerTeacherRegularizedPPO(PPO):
    """PPO with an optional frozen feedforward Ranger teacher action regularizer.

    Rollouts are always generated by the recurrent student policy. The teacher is
    queried only inside PPO minibatch updates and never controls the environment.
    ``critic_only`` provides a short bootstrap phase for the initially untrained
    recurrent critic while leaving actor/std parameters untouched.
    """

    def __init__(
        self,
        *args,
        teacher_loss_coef: float = 0.0,
        teacher_checkpoint: str | None = None,
        teacher_suspension_loss_weight: float = 1.0,
        teacher_wheel_loss_weight: float = 1.0,
        teacher_stop_phase_wheel_weight: float = 0.0,
        actor_loss_scale: float = 1.0,
        ppo_surrogate_scale: float = 1.0,
        actor_learning_rate: float | None = None,
        actor_train_scope: str = "all",
        large_heading_action_prior_coef: float = 0.0,
        large_heading_action_prior_start: float = 0.70,
        large_heading_action_prior_full: float = 1.05,
        large_heading_action_prior_common_target: float = 0.45,
        large_heading_action_prior_turn_gain: float = 0.55,
        critic_only: bool = False,
        diagnostic_only: bool = False,
        critic_relearning: bool = False,
        critic_relearning_return_lam: float = 1.0,
        critic_relearning_common_delta: float = 0.25,
        critic_relearning_turn_scale: float = 0.35,
        critic_relearning_perturb_period: int = 48,
        critic_relearning_perturb_burst: int = 12,
        **kwargs,
    ) -> None:
        super().__init__(*args, **kwargs)
        if self.rnd is not None:
            raise NotImplementedError("RangerTeacherRegularizedPPO does not currently support RND.")
        if self.symmetry is not None:
            raise NotImplementedError("RangerTeacherRegularizedPPO does not currently support symmetry augmentation.")
        if not getattr(self.policy, "is_recurrent", False):
            raise TypeError("RangerTeacherRegularizedPPO requires a recurrent student policy.")
        if teacher_loss_coef < 0.0:
            raise ValueError(f"teacher_loss_coef must be non-negative, got {teacher_loss_coef}.")
        if teacher_suspension_loss_weight < 0.0 or teacher_wheel_loss_weight < 0.0:
            raise ValueError("Teacher action loss weights must be non-negative.")
        if not 0.0 <= teacher_stop_phase_wheel_weight <= 1.0:
            raise ValueError(
                "teacher_stop_phase_wheel_weight must be in [0, 1], got "
                f"{teacher_stop_phase_wheel_weight}."
            )

        self.teacher_loss_coef = float(teacher_loss_coef)
        self.teacher_checkpoint = None if teacher_checkpoint is None else str(teacher_checkpoint)
        self.teacher_suspension_loss_weight = float(teacher_suspension_loss_weight)
        self.teacher_wheel_loss_weight = float(teacher_wheel_loss_weight)
        self.teacher_stop_phase_wheel_weight = float(teacher_stop_phase_wheel_weight)
        if actor_loss_scale <= 0.0:
            raise ValueError(f"actor_loss_scale must be positive, got {actor_loss_scale}.")
        self.actor_loss_scale = float(actor_loss_scale)
        if ppo_surrogate_scale < 0.0:
            raise ValueError(f"ppo_surrogate_scale must be non-negative, got {ppo_surrogate_scale}.")
        self.ppo_surrogate_scale = float(ppo_surrogate_scale)
        if actor_learning_rate is not None and actor_learning_rate <= 0.0:
            raise ValueError(f"actor_learning_rate must be positive when provided, got {actor_learning_rate}.")
        self.actor_learning_rate = None if actor_learning_rate is None else float(actor_learning_rate)
        self.actor_train_scope = str(actor_train_scope)
        if self.actor_train_scope not in {"all", "wheel_head", "wheel_residual"}:
            raise ValueError(
                f"Unsupported actor_train_scope={self.actor_train_scope!r}; "
                "expected 'all', 'wheel_head', or 'wheel_residual'."
            )
        if self.actor_train_scope != "all" and self.actor_learning_rate is None:
            raise ValueError("A restricted actor_train_scope requires actor_learning_rate / split optimizer mode.")
        if self.actor_learning_rate is not None:
            actor_params = []
            critic_params = []
            for name, parameter in self.policy.named_parameters():
                if name.startswith("actor.") or name == "log_std":
                    train_actor_parameter = self.actor_train_scope == "all"
                    if self.actor_train_scope == "wheel_head":
                        train_actor_parameter = name.startswith("actor.wheel_head.")
                    elif self.actor_train_scope == "wheel_residual":
                        train_actor_parameter = name.startswith("actor.wheel_goal_residual.")
                    parameter.requires_grad_(train_actor_parameter)
                    if train_actor_parameter:
                        actor_params.append(parameter)
                elif name.startswith("critic."):
                    parameter.requires_grad_(True)
                    critic_params.append(parameter)
                else:
                    raise RuntimeError(f"Unclassified policy parameter for split optimizer: {name}")
            if not actor_params:
                raise RuntimeError(f"actor_train_scope={self.actor_train_scope!r} selected no actor parameters.")
            self.optimizer = torch.optim.Adam(
                [
                    {"params": actor_params, "lr": self.actor_learning_rate, "name": "actor"},
                    {"params": critic_params, "lr": self.learning_rate, "name": "critic"},
                ]
            )
        if large_heading_action_prior_coef < 0.0:
            raise ValueError("large_heading_action_prior_coef must be non-negative.")
        if large_heading_action_prior_full <= large_heading_action_prior_start:
            raise ValueError("large_heading_action_prior_full must be greater than large_heading_action_prior_start.")
        self.large_heading_action_prior_coef = float(large_heading_action_prior_coef)
        self.large_heading_action_prior_start = float(large_heading_action_prior_start)
        self.large_heading_action_prior_full = float(large_heading_action_prior_full)
        self.large_heading_action_prior_common_target = float(large_heading_action_prior_common_target)
        self.large_heading_action_prior_turn_gain = float(large_heading_action_prior_turn_gain)
        self.critic_only = bool(critic_only)
        self.diagnostic_only = bool(diagnostic_only)
        self.critic_relearning = bool(critic_relearning)
        self.critic_relearning_return_lam = float(critic_relearning_return_lam)
        self.critic_relearning_common_delta = float(critic_relearning_common_delta)
        self.critic_relearning_turn_scale = float(critic_relearning_turn_scale)
        self.critic_relearning_perturb_period = int(critic_relearning_perturb_period)
        self.critic_relearning_perturb_burst = int(critic_relearning_perturb_burst)
        if self.critic_relearning and not self.critic_only:
            raise ValueError("critic_relearning requires critic_only=True.")
        if not 0.0 <= self.critic_relearning_return_lam <= 1.0:
            raise ValueError("critic_relearning_return_lam must be in [0, 1].")
        if self.critic_relearning_common_delta < 0.0:
            raise ValueError("critic_relearning_common_delta must be non-negative.")
        if not 0.0 <= self.critic_relearning_turn_scale <= 1.0:
            raise ValueError("critic_relearning_turn_scale must be in [0, 1].")
        if self.critic_relearning_perturb_period <= 0:
            raise ValueError("critic_relearning_perturb_period must be positive.")
        if not 0 <= self.critic_relearning_perturb_burst <= self.critic_relearning_perturb_period:
            raise ValueError("critic_relearning_perturb_burst must be within [0, perturb_period].")
        self._critic_relearning_step = 0
        self._critic_relearning_total_actions = 0
        self._critic_relearning_common_actions = 0
        self._critic_relearning_turn_actions = 0
        self.teacher = None

    def act(self, obs):
        """Use the frozen recurrent actor, with local wheel perturbations only for critic coverage."""

        actions = super().act(obs)
        if not self.critic_relearning or self.critic_relearning_perturb_burst == 0:
            return actions

        state_group = getattr(self.policy, "state_obs_group", "policy_state")
        state = obs[state_group]
        goal_start = int(self.policy.network_spec.goal_state_range[0])
        heading = torch.atan2(state[:, goal_start + 4], state[:, goal_start + 3])
        turning = heading.abs() >= (torch.pi / 12.0)
        burst_active = (
            self._critic_relearning_step % self.critic_relearning_perturb_period
        ) < self.critic_relearning_perturb_burst
        self._critic_relearning_step += 1
        self._critic_relearning_total_actions += int(actions.shape[0])
        if not burst_active:
            return actions

        env_index = torch.arange(actions.shape[0], device=actions.device)
        common_mask = turning & ((env_index % 4) == 2)
        turn_mask = turning & ((env_index % 4) == 3)
        if not torch.any(common_mask | turn_mask):
            return actions

        perturbed = actions.clone()
        wheel = perturbed[:, 4:8]
        left = wheel[:, :2].mean(dim=-1)
        right = wheel[:, 2:].mean(dim=-1)
        common = 0.5 * (left + right)
        turn = 0.5 * (right - left)
        new_common = common.clone()
        new_turn = turn.clone()

        if torch.any(common_mask):
            new_common[common_mask] = torch.clamp(
                common[common_mask] + self.critic_relearning_common_delta,
                min=-0.80,
                max=0.80,
            )
            turn_capacity = 0.98 - new_common[common_mask].abs()
            new_turn[common_mask] = torch.clamp(
                turn[common_mask],
                min=-turn_capacity,
                max=turn_capacity,
            )
        if torch.any(turn_mask):
            new_turn[turn_mask] = turn[turn_mask] * self.critic_relearning_turn_scale

        selected = common_mask | turn_mask
        new_left = new_common - new_turn
        new_right = new_common + new_turn
        left_shift = new_left - left
        right_shift = new_right - right
        wheel[selected, :2] = wheel[selected, :2] + left_shift[selected, None]
        wheel[selected, 2:] = wheel[selected, 2:] + right_shift[selected, None]
        perturbed[:, 4:8] = torch.clamp(wheel, min=-0.999, max=0.999)

        # Critic-only mode never uses action log-probabilities for optimization. Store the
        # actually executed perturbed command so diagnostics reflect the expanded dataset.
        self.transition.actions = perturbed.detach()
        self._critic_relearning_common_actions += int(common_mask.sum().item())
        self._critic_relearning_turn_actions += int(turn_mask.sum().item())
        return perturbed

    def compute_returns(self, obs) -> None:
        """Use a long lambda-return only during the dedicated critic-relearning phase."""

        if not self.critic_relearning:
            return super().compute_returns(obs)
        last_values = self.policy.evaluate(obs).detach()
        self.storage.compute_returns(
            last_values,
            self.gamma,
            self.critic_relearning_return_lam,
            normalize_advantage=not self.normalize_advantage_per_mini_batch,
        )

    def configure_teacher(self, teacher: nn.Module) -> None:
        """Attach a frozen feedforward teacher without adding it to student checkpoints."""

        teacher.eval()
        for parameter in teacher.parameters():
            parameter.requires_grad_(False)
        self.teacher = teacher

    @staticmethod
    def _grad_pair_stats(
        first_loss: torch.Tensor,
        second_loss: torch.Tensor,
        parameters: list[nn.Parameter],
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return actor-gradient norms and cosine similarity for two objectives."""

        zero = torch.zeros((), device=first_loss.device, dtype=first_loss.dtype)
        if not parameters or not first_loss.requires_grad or not second_loss.requires_grad:
            return zero, zero, zero
        first_grads = torch.autograd.grad(first_loss, parameters, retain_graph=True, allow_unused=True)
        second_grads = torch.autograd.grad(second_loss, parameters, retain_graph=True, allow_unused=True)
        first_sq = torch.zeros_like(zero)
        second_sq = torch.zeros_like(zero)
        dot = torch.zeros_like(zero)
        for first_grad, second_grad in zip(first_grads, second_grads):
            first_detached = None if first_grad is None else first_grad.detach()
            second_detached = None if second_grad is None else second_grad.detach()
            if first_detached is not None:
                first_sq = first_sq + first_detached.square().sum()
            if second_detached is not None:
                second_sq = second_sq + second_detached.square().sum()
            if first_detached is not None and second_detached is not None:
                dot = dot + (first_detached * second_detached).sum()
        first_norm = torch.sqrt(first_sq)
        second_norm = torch.sqrt(second_sq)
        cosine = dot / torch.clamp(first_norm * second_norm, min=1.0e-12)
        return first_norm, second_norm, cosine

    @staticmethod
    def _turn_direction_masks(
        heading: torch.Tensor,
        turn: torch.Tensor,
        actual_yaw_rate: torch.Tensor,
    ) -> dict[str, torch.Tensor]:
        """Split geometric counter-turns by their current yaw dynamics.

        The desired-yaw expression mirrors the current ShortGoal yaw-rate reward
        parameters (yaw_rate_max=0.45, heading_deadband=0.04, heading_scale=0.30).
        """

        turning = heading.abs() >= (torch.pi / 12.0)
        meaningful_turn = turn.abs() >= 0.05
        wrong_turn = turning & meaningful_turn & ((heading * turn) < 0.0)
        yaw_same_direction = (heading * actual_yaw_rate) > 0.0
        effective_heading = torch.sign(heading) * torch.relu(heading.abs() - 0.04)
        desired_yaw_rate = 0.45 * torch.tanh(effective_heading / 0.30)
        yaw_braking = (
            wrong_turn
            & yaw_same_direction
            & (actual_yaw_rate.abs() > (desired_yaw_rate.abs() + 0.02))
        )
        premature_counter = wrong_turn & yaw_same_direction & ~yaw_braking
        genuinely_worsening = wrong_turn & ~yaw_same_direction
        return {
            "turning_wrong_turn": wrong_turn,
            "turning_yaw_braking_counter_turn": yaw_braking,
            "turning_premature_counter_turn": premature_counter,
            "turning_genuinely_worsening_turn": genuinely_worsening,
        }

    def _advantage_diagnostics(
        self,
        obs_batch,
        actions_batch: torch.Tensor,
        advantages_batch: torch.Tensor,
        masks_batch: torch.Tensor,
    ) -> dict[str, float]:
        """Summarize rollout advantage by heading and bounded wheel-control modes."""

        state_group = getattr(self.policy, "state_obs_group", "policy_state")
        goal_start = int(self.policy.network_spec.goal_state_range[0])
        state_unpadded = unpad_trajectories(obs_batch[state_group], masks_batch)
        heading = torch.atan2(state_unpadded[..., goal_start + 4], state_unpadded[..., goal_start + 3])
        actual_yaw_rate = state_unpadded[..., 2]
        advantage = torch.squeeze(advantages_batch).detach()
        wheel = actions_batch[..., 4:8].detach()
        left = wheel[..., :2].mean(dim=-1)
        right = wheel[..., 2:].mean(dim=-1)
        common = 0.5 * (left + right)
        turn = 0.5 * (right - left)

        deg15 = torch.tensor(torch.pi / 12.0, device=heading.device, dtype=heading.dtype)
        deg45 = torch.tensor(torch.pi / 4.0, device=heading.device, dtype=heading.dtype)
        deg5 = torch.tensor(torch.pi / 36.0, device=heading.device, dtype=heading.dtype)
        abs_heading = heading.abs()
        abs_common = common.abs()
        abs_turn = turn.abs()
        turning = abs_heading >= deg15
        meaningful_turn = abs_turn >= 0.05
        direction_masks = self._turn_direction_masks(heading, turn, actual_yaw_rate)

        masks = {
            "heading_small": abs_heading < deg15,
            "heading_medium": (abs_heading >= deg15) & (abs_heading < deg45),
            "heading_large": abs_heading >= deg45,
            "goal_left": heading > deg5,
            "goal_center": abs_heading <= deg5,
            "goal_right": heading < -deg5,
            "common_low": abs_common < 0.4,
            "common_mid": (abs_common >= 0.4) & (abs_common < 0.7),
            "common_high": abs_common >= 0.7,
            "turn_low": abs_turn < 0.15,
            "turn_mid": (abs_turn >= 0.15) & (abs_turn < 0.35),
            "turn_high": abs_turn >= 0.35,
            "turning_high_common": turning & (abs_common >= 0.7),
            "turning_low_turn": turning & (abs_turn < 0.15),
            "turning_correct_turn": turning & meaningful_turn & ((heading * turn) > 0.0),
            **direction_masks,
        }
        result: dict[str, float] = {}
        for name, mask in masks.items():
            fraction = mask.to(advantage.dtype).mean()
            mean_advantage = advantage[mask].mean() if torch.any(mask) else torch.zeros_like(advantage.mean())
            result[f"advantage_{name}"] = float(mean_advantage.item())
            result[f"fraction_{name}"] = float(fraction.item())
        return result

    def _storage_credit_diagnostics(self) -> dict[str, float]:
        """Decompose rollout reward, TD residual, and raw GAE advantage by control regime."""

        rewards = self.storage.rewards.detach().squeeze(-1)
        dones = self.storage.dones.detach().squeeze(-1).to(torch.bool)
        values = self.storage.values.detach().squeeze(-1)
        returns = self.storage.returns.detach().squeeze(-1)
        actions = self.storage.actions.detach()
        state_group = getattr(self.policy, "state_obs_group", "policy_state")
        states = self.storage.observations[state_group].detach()
        goal_start = int(self.policy.network_spec.goal_state_range[0])
        heading = torch.atan2(states[..., goal_start + 4], states[..., goal_start + 3])

        wheel = actions[..., 4:8]
        left = wheel[..., :2].mean(dim=-1)
        right = wheel[..., 2:].mean(dim=-1)
        common = 0.5 * (left + right)
        turn = 0.5 * (right - left)

        # The final rollout step has no stored V(s_{t+1}); exclude it from the one-step TD diagnostic.
        reward = rewards[:-1]
        value = values[:-1]
        next_value = values[1:]
        done = dones[:-1]
        raw_advantage = (returns - values)[:-1]
        td_error = reward + self.gamma * (~done).to(value.dtype) * next_value - value
        heading = heading[:-1]
        common = common[:-1]
        turn = turn[:-1]
        actual_yaw_rate = states[..., 2][:-1]

        deg15 = torch.tensor(torch.pi / 12.0, device=heading.device, dtype=heading.dtype)
        deg45 = torch.tensor(torch.pi / 4.0, device=heading.device, dtype=heading.dtype)
        deg5 = torch.tensor(torch.pi / 36.0, device=heading.device, dtype=heading.dtype)
        abs_heading = heading.abs()
        abs_common = common.abs()
        abs_turn = turn.abs()
        turning = abs_heading >= deg15
        meaningful_turn = abs_turn >= 0.05
        direction_masks = self._turn_direction_masks(heading, turn, actual_yaw_rate)
        masks = {
            "heading_small": abs_heading < deg15,
            "heading_medium": (abs_heading >= deg15) & (abs_heading < deg45),
            "heading_large": abs_heading >= deg45,
            "goal_left": heading > deg5,
            "goal_center": abs_heading <= deg5,
            "goal_right": heading < -deg5,
            "common_low": abs_common < 0.4,
            "common_mid": (abs_common >= 0.4) & (abs_common < 0.7),
            "common_high": abs_common >= 0.7,
            "turn_low": abs_turn < 0.15,
            "turn_mid": (abs_turn >= 0.15) & (abs_turn < 0.35),
            "turn_high": abs_turn >= 0.35,
            "turning_high_common": turning & (abs_common >= 0.7),
            "turning_low_turn": turning & (abs_turn < 0.15),
            "turning_correct_turn": turning & meaningful_turn & ((heading * turn) > 0.0),
            **direction_masks,
        }
        signals = {
            "reward": reward,
            "td": td_error,
            "raw_advantage": raw_advantage,
            "value": value,
            "return": returns[:-1],
        }
        result: dict[str, float] = {}
        for bucket_name, mask in masks.items():
            result[f"credit_fraction_{bucket_name}"] = float(mask.to(reward.dtype).mean().item())
            for signal_name, signal in signals.items():
                mean_signal = signal[mask].mean() if torch.any(mask) else torch.zeros((), device=signal.device)
                result[f"credit_{signal_name}_{bucket_name}"] = float(mean_signal.item())
        result["credit_reward_all"] = float(reward.mean().item())
        result["credit_td_all"] = float(td_error.mean().item())
        result["credit_raw_advantage_all"] = float(raw_advantage.mean().item())

        # Critic value-shape diagnostics. ShortGoal long-term command encoding is
        # [goal_dir_x, goal_dir_y, near_distance, log2(1 + distance), velocity_toward_goal].
        full_heading = torch.atan2(states[..., goal_start + 4], states[..., goal_start + 3])
        full_abs_heading = full_heading.abs()
        global_log_distance = states[..., goal_start + 6]
        full_distance = torch.pow(torch.tensor(2.0, device=states.device, dtype=states.dtype), global_log_distance) - 1.0
        full_velocity_toward = states[..., goal_start + 7]
        full_actual_yaw = states[..., 2]
        heading_sign = torch.sign(full_heading)
        full_correct_yaw_component = heading_sign * full_actual_yaw
        full_value = values

        def _pearson(x: torch.Tensor, y: torch.Tensor) -> float:
            x_flat = x.reshape(-1).to(torch.float32)
            y_flat = y.reshape(-1).to(torch.float32)
            x_centered = x_flat - x_flat.mean()
            y_centered = y_flat - y_flat.mean()
            denom = torch.sqrt(x_centered.square().sum() * y_centered.square().sum())
            if float(denom.item()) <= 1.0e-12:
                return 0.0
            return float(((x_centered * y_centered).sum() / denom).item())

        result["critic_corr_value_distance"] = _pearson(full_value, full_distance)
        result["critic_corr_value_abs_heading"] = _pearson(full_value, full_abs_heading)
        result["critic_corr_value_velocity_toward"] = _pearson(full_value, full_velocity_toward)
        result["critic_corr_value_correct_yaw_component"] = _pearson(full_value, full_correct_yaw_component)

        # Compare value sensitivity to heading while controlling coarsely for distance.
        distance_bands = {
            "distance_near": full_distance < 3.0,
            "distance_mid": (full_distance >= 3.0) & (full_distance < 6.0),
            "distance_far": full_distance >= 6.0,
        }
        heading_bands = {
            "heading_small": full_abs_heading < deg15,
            "heading_medium": (full_abs_heading >= deg15) & (full_abs_heading < deg45),
            "heading_large": full_abs_heading >= deg45,
        }
        for distance_name, distance_mask in distance_bands.items():
            result[f"critic_fraction_{distance_name}"] = float(distance_mask.to(full_value.dtype).mean().item())
            for heading_name, heading_mask in heading_bands.items():
                joint_mask = distance_mask & heading_mask
                mean_value = full_value[joint_mask].mean() if torch.any(joint_mask) else torch.zeros((), device=full_value.device)
                result[f"critic_value_{distance_name}_{heading_name}"] = float(mean_value.item())
                result[f"critic_fraction_{distance_name}_{heading_name}"] = float(
                    joint_mask.to(full_value.dtype).mean().item()
                )

        # Critic-free finite-horizon discounted reward-to-go. These signals answer whether
        # a control regime is actually followed by better environment rewards, independent
        # of the learned value function. Only starting points with the full requested
        # horizon inside the rollout are included.
        full_heading = torch.atan2(states[..., goal_start + 4], states[..., goal_start + 3])
        full_abs_common = (0.5 * (left + right)).abs()
        full_turn = 0.5 * (right - left)
        full_abs_turn = full_turn.abs()
        for horizon in (30, 60, 120, 180):
            if rewards.shape[0] < horizon:
                continue
            valid_steps = rewards.shape[0] - horizon + 1
            discounted = torch.zeros_like(rewards[:valid_steps])
            alive = torch.ones_like(discounted)
            discount = 1.0
            for offset in range(horizon):
                discounted = discounted + discount * alive * rewards[offset : offset + valid_steps]
                alive = alive * (~dones[offset : offset + valid_steps]).to(alive.dtype)
                discount *= self.gamma

            h_heading = full_heading[:valid_steps]
            h_abs_heading = h_heading.abs()
            h_turn = full_turn[:valid_steps]
            h_abs_turn = full_abs_turn[:valid_steps]
            h_abs_common = full_abs_common[:valid_steps]
            h_turning = h_abs_heading >= deg15
            h_meaningful_turn = h_abs_turn >= 0.05
            h_direction_masks = self._turn_direction_masks(
                h_heading,
                h_turn,
                full_actual_yaw[:valid_steps],
            )
            horizon_masks = {
                "turning_high_common": h_turning & (h_abs_common >= 0.7),
                "turning_low_turn": h_turning & (h_abs_turn < 0.15),
                "turning_correct_turn": h_turning & h_meaningful_turn & ((h_heading * h_turn) > 0.0),
                **h_direction_masks,
            }
            result[f"credit_rtg{horizon}_all"] = float(discounted.mean().item())
            result[f"critic_corr_value_rtg{horizon}"] = _pearson(full_value[:valid_steps], discounted)
            result[f"rtg{horizon}_corr_distance"] = _pearson(discounted, full_distance[:valid_steps])
            result[f"rtg{horizon}_corr_abs_heading"] = _pearson(discounted, full_abs_heading[:valid_steps])
            result[f"rtg{horizon}_corr_velocity_toward"] = _pearson(discounted, full_velocity_toward[:valid_steps])
            result[f"rtg{horizon}_corr_correct_yaw_component"] = _pearson(
                discounted, full_correct_yaw_component[:valid_steps]
            )
            if horizon == 120:
                features = torch.stack(
                    (
                        full_distance[:valid_steps],
                        full_abs_heading[:valid_steps],
                        full_velocity_toward[:valid_steps],
                        full_correct_yaw_component[:valid_steps],
                    ),
                    dim=-1,
                ).reshape(-1, 4).to(torch.float32)
                feature_mean = features.mean(dim=0, keepdim=True)
                feature_std = features.std(dim=0, keepdim=True).clamp_min(1.0e-6)
                x = (features - feature_mean) / feature_std
                x = torch.cat((x, torch.ones((x.shape[0], 1), device=x.device, dtype=x.dtype)), dim=1)
                for target_name, target_tensor in (
                    ("value", full_value[:valid_steps]),
                    ("rtg120", discounted),
                ):
                    y = target_tensor.reshape(-1, 1).to(torch.float32)
                    y = (y - y.mean()) / y.std().clamp_min(1.0e-6)
                    beta = torch.linalg.lstsq(x, y).solution[:4, 0]
                    for feature_name, coefficient in zip(
                        ("distance", "abs_heading", "velocity_toward", "correct_yaw_component"), beta
                    ):
                        result[f"critic_regression_{target_name}_beta_{feature_name}"] = float(coefficient.item())
            for bucket_name, mask in horizon_masks.items():
                mean_rtg = discounted[mask].mean() if torch.any(mask) else torch.zeros((), device=discounted.device)
                result[f"credit_rtg{horizon}_{bucket_name}"] = float(mean_rtg.item())
                result[f"credit_rtg{horizon}_fraction_{bucket_name}"] = float(
                    mask.to(discounted.dtype).mean().item()
                )
            if horizon == 120:
                for distance_name, distance_mask_full in distance_bands.items():
                    distance_mask = distance_mask_full[:valid_steps]
                    for heading_name, heading_mask_full in heading_bands.items():
                        joint_mask = distance_mask & heading_mask_full[:valid_steps]
                        mean_rtg = discounted[joint_mask].mean() if torch.any(joint_mask) else torch.zeros((), device=discounted.device)
                        result[f"rtg120_{distance_name}_{heading_name}"] = float(mean_rtg.item())
        return result

    def _teacher_targets(self, obs_batch, masks_batch: torch.Tensor) -> torch.Tensor:
        """Evaluate the feedforward teacher on padded observations and unpad identically to the student."""

        if self.teacher is None:
            raise RuntimeError("Teacher regularization is enabled, but no teacher has been configured.")
        if masks_batch is None or masks_batch.ndim != 2:
            raise ValueError("Teacher regularization expects recurrent masks with shape [time, trajectories].")

        time_steps, num_trajectories = masks_batch.shape
        flat_obs = obs_batch.reshape(-1)
        with torch.inference_mode():
            teacher_flat = self.teacher.act_inference(flat_obs)
        teacher_padded = teacher_flat.reshape(time_steps, num_trajectories, -1)
        teacher_unpadded = unpad_trajectories(teacher_padded, masks_batch)
        # The legacy V10 teacher was trained with an unbounded Gaussian/linear actor,
        # while both Ranger action terms execute normalized commands after safety
        # clipping to [-1, 1].  The bounded recurrent student should therefore match
        # the teacher's executed normalized command, not its unbounded raw network output.
        return torch.clamp(teacher_unpadded, min=-1.0, max=1.0)

    def _stop_phase_mask(self, obs_batch, masks_batch: torch.Tensor) -> torch.Tensor:
        """Recover the historical ShortGoal stop flag from each PPO minibatch observation."""

        state_group = getattr(self.policy, "state_obs_group", "policy_state")
        network_spec = getattr(self.policy, "network_spec", None)
        if network_spec is None or not hasattr(network_spec, "goal_state_range"):
            raise AttributeError("Recurrent Ranger policy must expose network_spec.goal_state_range.")
        goal_start = int(network_spec.goal_state_range[0])
        stop_phase_index = goal_start + 2
        state_padded = obs_batch[state_group]
        if state_padded.shape[-1] <= stop_phase_index:
            raise ValueError(
                f"policy_state has dim {state_padded.shape[-1]}, cannot read stop flag index {stop_phase_index}."
            )
        stop_padded = state_padded[..., stop_phase_index : stop_phase_index + 1]
        stop_unpadded = unpad_trajectories(stop_padded, masks_batch).squeeze(-1)
        return stop_unpadded > 0.5

    def _large_heading_action_prior_loss(
        self,
        student_mean: torch.Tensor,
        obs_batch,
        masks_batch: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """Direct student-only wheel prior used for temporary large-heading repair.

        This loss never queries the V10 teacher. It maps the policy's own heading observation to a
        semantic differential-drive target: a moderate forward arc common-mode and a signed turn-mode
        proportional to ``sin(heading)``. The loss is normalized over active large-heading samples so its scale
        does not depend on how frequently the repair states occur in a minibatch.
        """

        if student_mean.shape[-1] != 8:
            raise ValueError(f"Expected 8 student actions, got shape={tuple(student_mean.shape)}")
        state_group = getattr(self.policy, "state_obs_group", "policy_state")
        network_spec = getattr(self.policy, "network_spec", None)
        if network_spec is None or not hasattr(network_spec, "goal_state_range"):
            raise AttributeError("Recurrent Ranger policy must expose network_spec.goal_state_range.")
        goal_start = int(network_spec.goal_state_range[0])
        state_padded = obs_batch[state_group]
        heading_xy_padded = state_padded[..., goal_start + 3 : goal_start + 5]
        heading_xy = unpad_trajectories(heading_xy_padded, masks_batch)
        heading = torch.atan2(heading_xy[..., 1], heading_xy[..., 0])
        heading_abs = heading.abs()
        gate = torch.clamp(
            (heading_abs - self.large_heading_action_prior_start)
            / max(self.large_heading_action_prior_full - self.large_heading_action_prior_start, 1.0e-6),
            min=0.0,
            max=1.0,
        )
        non_stop = (~self._stop_phase_mask(obs_batch, masks_batch)).to(student_mean.dtype)
        gate = gate.to(student_mean.dtype) * non_stop

        wheel_action = student_mean[..., 4:8]
        left_mean = wheel_action[..., :2].mean(dim=-1)
        right_mean = wheel_action[..., 2:].mean(dim=-1)
        common_mode = 0.5 * (left_mean + right_mean)
        turn_mode = 0.5 * (right_mean - left_mean)
        desired_turn = self.large_heading_action_prior_turn_gain * torch.sin(heading).to(student_mean.dtype)

        desired_common = student_mean.new_full(common_mode.shape, self.large_heading_action_prior_common_target)
        common_sq = torch.square(common_mode - desired_common)
        turn_sq = torch.square(turn_mode - desired_turn)
        gate_sum = gate.sum()
        if float(gate_sum.detach().item()) <= 1.0e-8:
            zero = student_mean.sum() * 0.0
            return zero, zero.detach(), zero.detach(), zero.detach()
        loss = torch.sum(gate * (common_sq + turn_sq)) / gate_sum
        fraction = (gate > 0.0).to(student_mean.dtype).mean()
        common_abs = torch.sum(gate * (common_mode - desired_common).abs()) / gate_sum
        turn_error_abs = torch.sum(gate * (turn_mode - desired_turn).abs()) / gate_sum
        return loss, fraction.detach(), common_abs.detach(), turn_error_abs.detach()

    def _teacher_action_loss(
        self,
        student_mean: torch.Tensor,
        teacher_mean: torch.Tensor,
        stop_phase_mask: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        if student_mean.shape != teacher_mean.shape:
            raise ValueError(
                f"Student/teacher action shape mismatch: {tuple(student_mean.shape)} vs {tuple(teacher_mean.shape)}."
            )
        if student_mean.shape[-1] != 8:
            raise ValueError(f"Ranger teacher action loss expects 8 actions, got {student_mean.shape[-1]}.")

        squared_error = (student_mean - teacher_mean).square()
        suspension_loss = squared_error[..., :4].mean()
        wheel_mse_per_sample = squared_error[..., 4:].mean(dim=-1)
        wheel_weights = torch.where(
            stop_phase_mask,
            torch.full_like(wheel_mse_per_sample, self.teacher_stop_phase_wheel_weight),
            torch.ones_like(wheel_mse_per_sample),
        )
        wheel_loss = (wheel_mse_per_sample * wheel_weights).mean()
        total = (
            self.teacher_suspension_loss_weight * suspension_loss
            + self.teacher_wheel_loss_weight * wheel_loss
        )
        cosine = F.cosine_similarity(student_mean, teacher_mean, dim=-1, eps=1.0e-8).mean()
        return total, suspension_loss, wheel_loss, cosine

    def update(self) -> dict[str, float]:
        mean_value_loss = 0.0
        mean_surrogate_loss = 0.0
        mean_entropy = 0.0
        mean_teacher_action_loss = 0.0
        mean_teacher_suspension_loss = 0.0
        mean_teacher_wheel_loss = 0.0
        mean_teacher_weighted_loss = 0.0
        mean_teacher_action_cosine = 0.0
        mean_teacher_non_stop_fraction = 0.0
        mean_ppo_actor_grad_norm = 0.0
        mean_teacher_actor_grad_norm = 0.0
        mean_ppo_teacher_grad_cosine = 0.0
        mean_applied_actor_grad_norm = 0.0
        mean_applied_critic_grad_norm = 0.0
        mean_surrogate_mean_grad_norm = 0.0
        mean_entropy_mean_grad_norm = 0.0
        mean_surrogate_entropy_mean_grad_cosine = 0.0
        mean_surrogate_logstd_grad_norm = 0.0
        mean_entropy_logstd_grad_norm = 0.0
        mean_surrogate_entropy_logstd_grad_cosine = 0.0
        mean_large_heading_action_prior_loss = 0.0
        mean_large_heading_action_prior_fraction = 0.0
        mean_large_heading_action_prior_common_abs = 0.0
        mean_large_heading_action_prior_turn_error_abs = 0.0
        mean_action_prior_actor_grad_norm = 0.0
        mean_surrogate_action_prior_grad_cosine = 0.0
        minibatch_grad_cosines: list[float] = []
        advantage_sums: dict[str, float] = {}

        if self.diagnostic_only:
            layout = []
            for name in ("rewards", "dones", "values", "returns", "advantages", "actions", "observations"):
                value = getattr(self.storage, name, None)
                if value is None:
                    layout.append(f"{name}=None")
                elif hasattr(value, "shape"):
                    layout.append(f"{name}:shape={tuple(value.shape)}")
                else:
                    layout.append(f"{name}:type={type(value).__name__}")
            print("[TeacherPPO][DiagnosticStorage] " + " | ".join(layout))
        if self.diagnostic_only or self.critic_relearning:
            credit_diagnostics = self._storage_credit_diagnostics()
        else:
            credit_diagnostics = {}

        if self.policy.is_recurrent:
            generator = self.storage.recurrent_mini_batch_generator(self.num_mini_batches, self.num_learning_epochs)
        else:
            raise TypeError("RangerTeacherRegularizedPPO requires recurrent rollout storage.")

        actor_parameters = [parameter for parameter in self.policy.actor.parameters() if parameter.requires_grad]
        log_std_parameters = [self.policy.log_std] if getattr(self.policy, 'log_std', None) is not None and self.policy.log_std.requires_grad else []
        optimization_actor_parameters = [
            parameter
            for name, parameter in self.policy.named_parameters()
            if parameter.requires_grad and (name.startswith("actor.") or name == "log_std")
        ]
        critic_parameters = [
            parameter
            for name, parameter in self.policy.named_parameters()
            if parameter.requires_grad and name.startswith("critic.")
        ]

        for (
            obs_batch,
            actions_batch,
            target_values_batch,
            advantages_batch,
            returns_batch,
            old_actions_log_prob_batch,
            old_mu_batch,
            old_sigma_batch,
            hidden_states_batch,
            masks_batch,
        ) in generator:
            advantage_diag_values = self._advantage_diagnostics(
                obs_batch, actions_batch, advantages_batch, masks_batch
            )
            for key, value in advantage_diag_values.items():
                advantage_sums[key] = advantage_sums.get(key, 0.0) + value

            if self.normalize_advantage_per_mini_batch:
                with torch.no_grad():
                    advantages_batch = (advantages_batch - advantages_batch.mean()) / (advantages_batch.std() + 1.0e-8)

            if self.critic_only:
                value_batch = self.policy.evaluate(obs_batch, masks=masks_batch, hidden_state=hidden_states_batch[1])
                surrogate_loss = torch.zeros((), device=value_batch.device, dtype=value_batch.dtype)
                entropy_mean = torch.zeros_like(surrogate_loss)
            else:
                self.policy.act(obs_batch, masks=masks_batch, hidden_state=hidden_states_batch[0])
                actions_log_prob_batch = self.policy.get_actions_log_prob(actions_batch)
                value_batch = self.policy.evaluate(obs_batch, masks=masks_batch, hidden_state=hidden_states_batch[1])
                mu_batch = self.policy.action_mean
                sigma_batch = self.policy.action_std
                bounded_mu_batch = self.policy.bounded_action_mean
                entropy_batch = self.policy.entropy
                entropy_mean = entropy_batch.mean()

                if not self.diagnostic_only and self.desired_kl is not None and self.schedule == "adaptive":
                    with torch.inference_mode():
                        kl = torch.sum(
                            torch.log(sigma_batch / old_sigma_batch + 1.0e-5)
                            + (torch.square(old_sigma_batch) + torch.square(old_mu_batch - mu_batch))
                            / (2.0 * torch.square(sigma_batch))
                            - 0.5,
                            axis=-1,
                        )
                        kl_mean = torch.mean(kl)
                        if self.is_multi_gpu:
                            torch.distributed.all_reduce(kl_mean, op=torch.distributed.ReduceOp.SUM)
                            kl_mean /= self.gpu_world_size
                        if self.gpu_global_rank == 0:
                            if kl_mean > self.desired_kl * 2.0:
                                self.learning_rate = max(1.0e-5, self.learning_rate / 1.5)
                            elif kl_mean < self.desired_kl / 2.0 and kl_mean > 0.0:
                                self.learning_rate = min(1.0e-2, self.learning_rate * 1.5)
                        if self.is_multi_gpu:
                            lr_tensor = torch.tensor(self.learning_rate, device=self.device)
                            torch.distributed.broadcast(lr_tensor, src=0)
                            self.learning_rate = lr_tensor.item()
                        for param_group in self.optimizer.param_groups:
                            param_group["lr"] = self.learning_rate

                ratio = torch.exp(actions_log_prob_batch - torch.squeeze(old_actions_log_prob_batch))
                surrogate = -torch.squeeze(advantages_batch) * ratio
                surrogate_clipped = -torch.squeeze(advantages_batch) * torch.clamp(
                    ratio, 1.0 - self.clip_param, 1.0 + self.clip_param
                )
                surrogate_loss = torch.max(surrogate, surrogate_clipped).mean()

            if self.use_clipped_value_loss:
                value_clipped = target_values_batch + (value_batch - target_values_batch).clamp(
                    -self.clip_param, self.clip_param
                )
                value_losses = (value_batch - returns_batch).pow(2)
                value_losses_clipped = (value_clipped - returns_batch).pow(2)
                value_loss = torch.max(value_losses, value_losses_clipped).mean()
            else:
                value_loss = (returns_batch - value_batch).pow(2).mean()

            surrogate_mean_grad_norm = torch.zeros_like(value_loss)
            entropy_mean_grad_norm = torch.zeros_like(value_loss)
            surrogate_entropy_mean_grad_cosine = torch.zeros_like(value_loss)
            surrogate_logstd_grad_norm = torch.zeros_like(value_loss)
            entropy_logstd_grad_norm = torch.zeros_like(value_loss)
            surrogate_entropy_logstd_grad_cosine = torch.zeros_like(value_loss)
            large_heading_action_prior_loss = torch.zeros_like(value_loss)
            large_heading_action_prior_fraction = torch.zeros_like(value_loss)
            large_heading_action_prior_common_abs = torch.zeros_like(value_loss)
            large_heading_action_prior_turn_error_abs = torch.zeros_like(value_loss)
            action_prior_actor_grad_norm = torch.zeros_like(value_loss)
            surrogate_action_prior_grad_cosine = torch.zeros_like(value_loss)

            if self.critic_only:
                teacher_action_loss = torch.zeros_like(value_loss)
                teacher_suspension_loss = torch.zeros_like(value_loss)
                teacher_wheel_loss = torch.zeros_like(value_loss)
                teacher_action_cosine = torch.zeros_like(value_loss)
                non_stop_fraction = torch.zeros_like(value_loss)
                weighted_teacher_loss = torch.zeros_like(value_loss)
                ppo_actor_grad_norm = torch.zeros_like(value_loss)
                teacher_actor_grad_norm = torch.zeros_like(value_loss)
                ppo_teacher_grad_cosine = torch.zeros_like(value_loss)
                loss = self.value_loss_coef * value_loss
            else:
                teacher_action_loss = torch.zeros_like(value_loss)
                teacher_suspension_loss = torch.zeros_like(value_loss)
                teacher_wheel_loss = torch.zeros_like(value_loss)
                teacher_action_cosine = torch.zeros_like(value_loss)
                non_stop_fraction = torch.zeros_like(value_loss)

                if self.teacher_loss_coef > 0.0:
                    teacher_mean = self._teacher_targets(obs_batch, masks_batch)
                    stop_phase_mask = self._stop_phase_mask(obs_batch, masks_batch)
                    (
                        teacher_action_loss,
                        teacher_suspension_loss,
                        teacher_wheel_loss,
                        teacher_action_cosine,
                    ) = self._teacher_action_loss(bounded_mu_batch, teacher_mean, stop_phase_mask)
                    non_stop_fraction = (~stop_phase_mask).to(bounded_mu_batch.dtype).mean()

                if self.large_heading_action_prior_coef > 0.0:
                    (
                        large_heading_action_prior_loss,
                        large_heading_action_prior_fraction,
                        large_heading_action_prior_common_abs,
                        large_heading_action_prior_turn_error_abs,
                    ) = self._large_heading_action_prior_loss(bounded_mu_batch, obs_batch, masks_batch)

                weighted_teacher_loss = self.teacher_loss_coef * teacher_action_loss
                if self.teacher_loss_coef > 0.0:
                    (
                        ppo_actor_grad_norm,
                        teacher_actor_grad_norm,
                        ppo_teacher_grad_cosine,
                    ) = self._grad_pair_stats(surrogate_loss, weighted_teacher_loss, actor_parameters)
                else:
                    ppo_actor_grad_norm = torch.zeros_like(value_loss)
                    teacher_actor_grad_norm = torch.zeros_like(value_loss)
                    ppo_teacher_grad_cosine = torch.zeros_like(value_loss)
                entropy_objective = -self.entropy_coef * entropy_mean
                if self.diagnostic_only:
                    (
                        surrogate_mean_grad_norm,
                        entropy_mean_grad_norm,
                        surrogate_entropy_mean_grad_cosine,
                    ) = self._grad_pair_stats(surrogate_loss, entropy_objective, actor_parameters)
                    (
                        surrogate_logstd_grad_norm,
                        entropy_logstd_grad_norm,
                        surrogate_entropy_logstd_grad_cosine,
                    ) = self._grad_pair_stats(surrogate_loss, entropy_objective, log_std_parameters)
                else:
                    surrogate_mean_grad_norm = torch.zeros_like(value_loss)
                    entropy_mean_grad_norm = torch.zeros_like(value_loss)
                    surrogate_entropy_mean_grad_cosine = torch.zeros_like(value_loss)
                    surrogate_logstd_grad_norm = torch.zeros_like(value_loss)
                    entropy_logstd_grad_norm = torch.zeros_like(value_loss)
                    surrogate_entropy_logstd_grad_cosine = torch.zeros_like(value_loss)
                weighted_action_prior_loss = self.large_heading_action_prior_coef * large_heading_action_prior_loss
                if self.large_heading_action_prior_coef > 0.0:
                    (
                        _,
                        action_prior_actor_grad_norm,
                        surrogate_action_prior_grad_cosine,
                    ) = self._grad_pair_stats(surrogate_loss, weighted_action_prior_loss, actor_parameters)
                else:
                    action_prior_actor_grad_norm = torch.zeros_like(value_loss)
                    surrogate_action_prior_grad_cosine = torch.zeros_like(value_loss)
                actor_side_loss = (
                    self.ppo_surrogate_scale * surrogate_loss
                    + entropy_objective
                    + weighted_teacher_loss
                    + weighted_action_prior_loss
                )
                loss = self.actor_loss_scale * actor_side_loss + self.value_loss_coef * value_loss

            if not self.diagnostic_only:
                self.optimizer.zero_grad()
                loss.backward()

                if self.is_multi_gpu:
                    self.reduce_parameters()

                if self.actor_learning_rate is not None:
                    actor_grad_norm = nn.utils.clip_grad_norm_(optimization_actor_parameters, self.max_grad_norm)
                    critic_grad_norm = nn.utils.clip_grad_norm_(critic_parameters, self.max_grad_norm)
                else:
                    global_grad_norm = nn.utils.clip_grad_norm_(self.policy.parameters(), self.max_grad_norm)
                    actor_grad_norm = global_grad_norm
                    critic_grad_norm = global_grad_norm
                self.optimizer.step()
                mean_applied_actor_grad_norm += float(actor_grad_norm.item())
                mean_applied_critic_grad_norm += float(critic_grad_norm.item())

            mean_value_loss += float(value_loss.item())
            mean_surrogate_loss += float(surrogate_loss.item())
            mean_entropy += float(entropy_mean.item())
            mean_teacher_action_loss += float(teacher_action_loss.item())
            mean_teacher_suspension_loss += float(teacher_suspension_loss.item())
            mean_teacher_wheel_loss += float(teacher_wheel_loss.item())
            mean_teacher_weighted_loss += float(weighted_teacher_loss.item())
            mean_teacher_action_cosine += float(teacher_action_cosine.item())
            mean_teacher_non_stop_fraction += float(non_stop_fraction.item())
            mean_ppo_actor_grad_norm += float(ppo_actor_grad_norm.item())
            mean_teacher_actor_grad_norm += float(teacher_actor_grad_norm.item())
            mean_ppo_teacher_grad_cosine += float(ppo_teacher_grad_cosine.item())
            mean_surrogate_mean_grad_norm += float(surrogate_mean_grad_norm.item())
            mean_entropy_mean_grad_norm += float(entropy_mean_grad_norm.item())
            mean_surrogate_entropy_mean_grad_cosine += float(surrogate_entropy_mean_grad_cosine.item())
            mean_surrogate_logstd_grad_norm += float(surrogate_logstd_grad_norm.item())
            mean_entropy_logstd_grad_norm += float(entropy_logstd_grad_norm.item())
            mean_surrogate_entropy_logstd_grad_cosine += float(surrogate_entropy_logstd_grad_cosine.item())
            mean_large_heading_action_prior_loss += float(large_heading_action_prior_loss.item())
            mean_large_heading_action_prior_fraction += float(large_heading_action_prior_fraction.item())
            mean_large_heading_action_prior_common_abs += float(large_heading_action_prior_common_abs.item())
            mean_large_heading_action_prior_turn_error_abs += float(large_heading_action_prior_turn_error_abs.item())
            mean_action_prior_actor_grad_norm += float(action_prior_actor_grad_norm.item())
            mean_surrogate_action_prior_grad_cosine += float(surrogate_action_prior_grad_cosine.item())
            minibatch_grad_cosines.append(float(ppo_teacher_grad_cosine.item()))

        num_updates = self.num_learning_epochs * self.num_mini_batches
        mean_value_loss /= num_updates
        mean_surrogate_loss /= num_updates
        mean_entropy /= num_updates
        mean_teacher_action_loss /= num_updates
        mean_teacher_suspension_loss /= num_updates
        mean_teacher_wheel_loss /= num_updates
        mean_teacher_weighted_loss /= num_updates
        mean_teacher_action_cosine /= num_updates
        mean_teacher_non_stop_fraction /= num_updates
        mean_ppo_actor_grad_norm /= num_updates
        mean_teacher_actor_grad_norm /= num_updates
        mean_ppo_teacher_grad_cosine /= num_updates
        mean_applied_actor_grad_norm /= num_updates
        mean_applied_critic_grad_norm /= num_updates
        mean_surrogate_mean_grad_norm /= num_updates
        mean_entropy_mean_grad_norm /= num_updates
        mean_surrogate_entropy_mean_grad_cosine /= num_updates
        mean_surrogate_logstd_grad_norm /= num_updates
        mean_entropy_logstd_grad_norm /= num_updates
        mean_surrogate_entropy_logstd_grad_cosine /= num_updates
        mean_large_heading_action_prior_loss /= num_updates
        mean_large_heading_action_prior_fraction /= num_updates
        mean_large_heading_action_prior_common_abs /= num_updates
        mean_large_heading_action_prior_turn_error_abs /= num_updates
        mean_action_prior_actor_grad_norm /= num_updates
        mean_surrogate_action_prior_grad_cosine /= num_updates
        mean_teacher_to_ppo_grad_ratio = mean_teacher_actor_grad_norm / max(mean_ppo_actor_grad_norm, 1.0e-12)
        advantage_means = {key: value / num_updates for key, value in advantage_sums.items()}

        self.storage.clear()

        metrics = {
            "value_function": mean_value_loss,
            "surrogate": mean_surrogate_loss,
            "entropy": mean_entropy,
            "teacher_action": mean_teacher_action_loss,
            "teacher_suspension": mean_teacher_suspension_loss,
            "teacher_wheel": mean_teacher_wheel_loss,
            "teacher_weighted": mean_teacher_weighted_loss,
            "teacher_action_cosine": mean_teacher_action_cosine,
            "teacher_non_stop_fraction": mean_teacher_non_stop_fraction,
            "ppo_actor_grad_norm": mean_ppo_actor_grad_norm,
            "teacher_actor_grad_norm": mean_teacher_actor_grad_norm,
            "teacher_to_ppo_grad_ratio": mean_teacher_to_ppo_grad_ratio,
            "ppo_teacher_grad_cosine": mean_ppo_teacher_grad_cosine,
            "diagnostic_only": float(self.diagnostic_only),
            "critic_relearning": float(self.critic_relearning),
            "actor_loss_scale": self.actor_loss_scale,
            "ppo_surrogate_scale": self.ppo_surrogate_scale,
            "actor_learning_rate": 0.0 if self.actor_learning_rate is None else self.actor_learning_rate,
            "applied_actor_grad_norm": mean_applied_actor_grad_norm,
            "applied_critic_grad_norm": mean_applied_critic_grad_norm,
            "surrogate_mean_grad_norm": mean_surrogate_mean_grad_norm,
            "entropy_mean_grad_norm": mean_entropy_mean_grad_norm,
            "surrogate_entropy_mean_grad_cosine": mean_surrogate_entropy_mean_grad_cosine,
            "surrogate_logstd_grad_norm": mean_surrogate_logstd_grad_norm,
            "entropy_logstd_grad_norm": mean_entropy_logstd_grad_norm,
            "surrogate_entropy_logstd_grad_cosine": mean_surrogate_entropy_logstd_grad_cosine,
            "large_heading_action_prior_coef": self.large_heading_action_prior_coef,
            "large_heading_action_prior": mean_large_heading_action_prior_loss,
            "large_heading_action_prior_fraction": mean_large_heading_action_prior_fraction,
            "large_heading_action_prior_common_abs": mean_large_heading_action_prior_common_abs,
            "large_heading_action_prior_turn_error_abs": mean_large_heading_action_prior_turn_error_abs,
            "action_prior_actor_grad_norm": mean_action_prior_actor_grad_norm,
            "surrogate_action_prior_grad_cosine": mean_surrogate_action_prior_grad_cosine,
        }
        if self.critic_relearning:
            total = max(self._critic_relearning_total_actions, 1)
            metrics["critic_relearning_common_perturb_fraction"] = self._critic_relearning_common_actions / total
            metrics["critic_relearning_turn_perturb_fraction"] = self._critic_relearning_turn_actions / total
            metrics["critic_relearning_return_lam"] = self.critic_relearning_return_lam
            self._critic_relearning_total_actions = 0
            self._critic_relearning_common_actions = 0
            self._critic_relearning_turn_actions = 0
        for minibatch_index, cosine in enumerate(minibatch_grad_cosines):
            metrics[f"ppo_teacher_grad_cosine_mb{minibatch_index}"] = cosine
        metrics.update(advantage_means)
        metrics.update(credit_diagnostics)
        return metrics
